# Generated by Django 3.2.3 on 2021-06-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizeraccount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizeraccount',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
